### PR TITLE
set cache: bundler in .travis.yml

### PR DESCRIPTION
**Pull request by bwitt**
only set `cache: bundler` in `.travis.yml`

### CODE REVIEW

**Comment by bwitt** [comment]
hmm this doesn't seem to have helped travis build times

**Comment by bwitt** [comment]
maybe cache: bundler will help in the future?

**Comment by bwitt** [comment]
I was hoping to speed up all gem installs not just the `bundler` one.  however adding `--no-document` didn't seem to do anything to gem install times (also I didn't see gem mentioning installing docs in the travis logs so maybe it's already not doing that?) so should probably remove `--no-document` entirely

**Comment by ZeroPointEnergy** [comment]
Yes bundler doesn't install docs and ri by default. I didn't take a look yet but I would guess it's slow because of the gems with the native extensions.

**Pull request merged**
