### PR TITLE
Fix report sanitization for new report types

### PR DESCRIPTION
**Pull request by ssgelm**
As promised in #315, this PR adds support for report formats 3 and 4.  A few new columns needed to be created for new fields in the report.  Right now they are not displayed in the UI but they do get properly added to the DB.

### CODE REVIEW

**Comment by ssgelm** [comment]
I just updated this branch with a fix for puppet 4.x where they changed the report format without documenting it. :disappointed: I have been running this in production for about 6 months now with no failed reports.

**Comment by sodabrew** [comment]
This is awesome, thank you!! I will follow up with some release engineering and merge.

**Comment by ssgelm** [comment]
I totally forgot about this PR and just noticed it sitting in my list of PRs.  Any chance of it getting merged?

**Comment by bwitt** [comment]
hmm recent merges have introduced some conflicts; @ssgelm can you take a look or maybe @ZeroPointEnergy has a copy that works?

**Comment by ZeroPointEnergy** [comment]
I have rebased and iterated on this PR and created a new one here https://github.com/sodabrew/puppet-dashboard/pull/354 . Thanks for your awesome work @ssgelm and sorry for the delay. I'm closing this as your rebased commits are all part of the new PR.

**Pull request closed without merging**
