### PR TITLE
permits :description param in new_node_groups

### PR DESCRIPTION
**Pull request by big32mike**
To add a :description to a NodeGroup upon creation, new_node_group must permit the :description command.
```
Started POST "/node_groups" for 127.0.0.1 at 2020-06-26 14:38:34 -0700
Processing by NodeGroupsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"cpgS7UPu3vVlZR9+2F9R6tKjJdslJGp3xolRnmNPDsZ+smcpy8ANhTmB1oJnPutHjMUQI8AHztgiErNRx7nBTw==", "force_create"=>"false", "node_group"=>{"name"=>"test_description", "description"=>"This doesn't get saved when creating a new group.", "parameter_attributes"=>[{"key"=>"", "value"=>""}], "assigned_node_class_ids"=>[""], "assigned_node_group_ids"=>[""], "assigned_node_ids"=>[""]}}
   (0.1ms)  BEGIN
  ↳ app/controllers/node_groups_controller.rb:19
Unpermitted parameter: :description
Unpermitted parameter: :description
Unpermitted parameter: :description
```

### CODE REVIEW

**Comment by sodabrew** [comment]
This is great, thank you! If there’s a test for creating a node group by api, please add a description to that test as well.

**Comment by sodabrew** [comment]
Specifically here: https://github.com/sodabrew/puppet-dashboard/blob/f3e7b34fbaf0880cd4271113165d0ebcae5940e6/spec/controllers/node_groups_controller_spec.rb#L13-L17 if I could bug you to add a `description` field in this test and we'll get this merged straight away!

**Comment by big32mike** [comment]
No problem.

**Comment by sodabrew** [comment]
Thank you!

**Pull request merged**
