### PR TITLE
Add content previously hosted at docs.puppetlabs.com

### PR DESCRIPTION
**Pull request by pdxmph**
This commit provides the Dashboard documentation previously hosted at
docs.puppetlabs.com. The content is formatted for use in a Jekyll site,
and may be easily ported to the Dashboard wiki with minimal
reformatting.

The content will also be available in the git history of the puppet-docs
repository:

https://github.com/puppetlabs/puppet-docs/tree/puppet-dashboard-pre-deletion

### CODE REVIEW

**Comment by jorhett** [comment]
@sodabrew is there any reason this hasn't been merged? It would solve #330

**Comment by evelynmitchell** [comment]
Why hasn't this been merged yet?

**Comment by sodabrew** [comment]
Due to my lack of time, with deepest apologies for the delay.

**Comment by 7yl4r** [comment]
Uhh... Isn't this a one-click fix?

**Comment by bwitt** [comment]
thanks for the contribution!   sorry for the delay

**Pull request merged**
