### PR TITLE
reset tags in reports since the format is different between puppet ve…

### PR DESCRIPTION
**Pull request by arnaudmm**
…rsions

Hello, Here is my fix about #320 
Tags are reseted to enable parsing. Tags are not used/displayed in puppet dashboard so I think it is a reasonable option.

### CODE REVIEW

**Comment by jorhett** [comment]
This isn't a complete fix. It works for some cases and not for others. I am still investigating why...

**Comment by sodabrew** [comment]
Thank you both very much for investigating puppet 4 reports!

**Comment by arnaudmm** [comment]
@jorhett don't hesitate to complete #320 with your field report

**Comment by arnaudmm** [comment]
Some feedback : I'm using this fix with success to parse puppet4 report with puppet4 (puppetserver 2.1.1-1puppetlabs1)

**Comment by jorhett** [comment]
Any progress on this? I believe that this would be a useful change to push in, and then add a feature request for adding tags functionality.  Right now it simply won't work with Puppet 4 at all.

**Comment by arnaudmm** [comment]
As I already said, It's ok for me, I'm using it in production with full puppet4 env (~150 nodes)
What would be great : adapt test case to pass automatic test..

**Comment by bwitt** [comment]
closing / reopening to get travis to re-run

**Comment by bwitt** [comment]
oh hmm the original repo has disappeared!  I will create a new PR

**Pull request closed without merging**
